from subprocess import call

#call(["python", "Task1Output.py"])
#call(["python", "Task2Printing statements.py"])
#call(["python", "Task3Variables Part 1.py"])
#call(["python", "Task4Variables Part 2.py"])
#call(["python", "Task5Progress check.py"])
#call(["python", "Task6Input.py"])
#call(["python", "Task7Test 1.py"])
#call(["python", "Task8Variable conversion (casting)Part 1.py"])
#call(["python", "Task9Variable conversion (casting)Part 2.py"])
#call(["python", "Task10Numbers.py"])
#call(["python", "Task11Working with numbers.py"])
#call(["python", "Task12Number progress check.py"])
#call(["python", "Task13Comments.py"])
#call(["python", "Task14Decimals and rounding numbers.py"])
#call(["python", "Task15Random Numbers.py"])
#call(["python", "Task16Selection with IF Statements.py"])
#call(["python", "Task18IF, ELIF and ELSE.py"])
#call(["python", "Task19Selection (IF) with numbers.py"])
#call(["python", "Task21Selection challenge.py"])
#call(["python", "Task22Logical operators.py"])
#call(["python", "Task23  Test 2Calculator.py"])
#call(["python", "Task24Count controlled iteration.py"])
#call(["python", "Task25Condition controlled iteration.py"])
#call(["python", "Task26Iteration challenges.py"])
#call(["python", "Task27Test 3Iteration.py"])
#call(["python", "Task28Checking Strings.py"])
#call(["python", "Task29Using operators with Strings.py"])
#call(["python", "Task30Other string thingsPart 1.py"])
#call(["python", "Task31Other string thingsPart 2.py"])
#call(["python", "Task32Creating and editing lists/arrays.py"])
#call(["python", "Task33Checking lists/arrays.py"])
#call(["python", "Task34Searching lists/arrays.py"])
#call(["python", "Task35Test 4Arrays and lists.py"])

#call(["python", "task0_ex2.py"])
#call(["python", "task0_ex1.py"])
#call(["python", "task0_ex3.py"])
call(["python", "Task0_ex4.py"])
#call(["python", "Task0Playground.py"])